version: "3"

services:
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./results:/app/results
